### PR TITLE
Support with API_KEY and API_SECRET

### PR DESCRIPTION
**Pull request by kenhys**
ref. https://docs.confluent.io/platform/current/schema-registry/develop/using.html#common-sr-api-usage-examples

### CODE REVIEW

**Comment by kenhys** [comment]
It should refere https://docs.confluent.io/platform/current/security/basic-auth.html#schema-registry

**Comment by kenhys** [comment]
```
$ find /etc/schema-registry/
/etc/schema-registry/
/etc/schema-registry/connect-avro-distributed.properties
/etc/schema-registry/connect-avro-standalone.properties
/etc/schema-registry/log4j.properties
/etc/schema-registry/jaas_config.file
/etc/schema-registry/password
/etc/schema-registry/schema-registry.properties
```

create jaas_config.file
```
$ cat jaas_config.file 
SchemaRegistry-Props {
  org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
  file="/etc/schema-registry/password"
  debug="true";
};
```

create pasword file

```
$ cat password 
test: OBF:1z0f1vu91vv11z0f,user,admin
```

Set properties for schema-registry.properties.
```
authentication.method=BASIC
authentication.roles=admin,developer,user,sr-user
authentication.realm=SchemaRegistry-Props
```
Then start `schema-registry-start /etc/schema-registry/schema-registry.properties`

**Comment by kenhys** [comment]
Got 401,

```
$ curl -v -u test:test http://localhost:8081/subjects
* About to connect() to localhost port 8081 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8081 (#0)
* Server auth using Basic with user 'test'
> GET /subjects HTTP/1.1
> Authorization: Basic dGVzdDp0ZXN0
> User-Agent: curl/7.29.0
> Host: localhost:8081
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
* Authentication problem. Ignoring this.
< WWW-Authenticate: basic realm="SchemaRegistry-Props"
< Content-Type: application/json;charset=iso-8859-1
< Content-Length: 43
< 
* Connection #0 to host localhost left intact
{"error_code":401,"message":"Unauthorized"}
```

**Comment by kenhys** [comment]
I've checked whether schema registry is running as expected.

```
 % curl --silent -u test:test http://localhost:8081/subjects | jq .
[
  "Kafka-value",
  "Kafka-key"
]
```

**Comment by kenhys** [comment]
I need sample avro data to verify.

**Comment by kenhys** [comment]
It should be formatted in the markdown table for parameters but currently, it is not the scope of this PR.

**Review by cosmo0920 — APPROVED** [review]
LGTM. Thanks for your work! :muscle:

**Pull request merged**
